name: Generate Book and send to github pages.
on: 
  push:
jobs:
  ebook:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      # Book generation
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate ebook from markdown
        run: bin/build

      # HTML publication as Github Page
      - name: Publish HTML
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: gh-pages
